### ISSUE TITLE
能添加新版egde驱动吗

### ISSUE THREAD

**Issue by gongdananyou** [lossme/TencentComicBook#13]

**Comment by lossme** [comment]
selenium应该支持的，参数里我加下就好

**Comment by gongdananyou** [comment]
> selenium应该支持的，参数里我加下就好
调用的时候还是报错了，我自己调试打开是没问题的，但是运行脚本就报错了
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found

**Comment by gongdananyou** [comment]
> selenium应该支持的，参数里我加下就好

谢谢

**Comment by lossme** [comment]
你更新下代码，看下能不能使用

**Comment by gongdananyou** [comment]
> 你更新下代码，看下能不能使用

已解决，单引号和双引号的问题，单引号报错，双引号就没问题了
