### ISSUE TITLE
这个软件是按哪程序来启动的，能说的细致一点吗？.py程序有点多，不是很懂，谢谢了

### ISSUE THREAD

**Issue by niuqudechongdong** [lossme/TencentComicBook#14]

**Comment by lossme** [comment]
你是想了解这个程序的运行方式还是说在使用上遇到了困难

**Comment by niuqudechongdong** [comment]
运行方式，因为我不是很懂编程，现在才刚写开始编程，所以不知道怎么运行这些程序

**Comment by lossme** [comment]
python -m xxx，这样是以模块的方式来运行脚本，其实是执行xxx模块里的 __main__.py 脚本。

**Comment by xxlcs** [comment]
我也是……python chromedrive 啥的都下载了一遍发现完全不会用这个包（；´д｀）ゞ没学过py完全看不懂是怎么使用的啊，放弃了放弃了

**Comment by lossme** [comment]
确保路径没问题
```sh
>>> git clone git@github.com:lossme/TencentComicBook.git
>>> cd TencentComicBook
>>> pip install -r requirements.txt
>>> python3 -m onepiece --help
```

**Comment by niuqudechongdong** [comment]
大佬，我下载好了这个程序，然后把manage.py拖到spyder里，运行了一下，然后在spyder里执行了pip install -r requirements.txt这一步（没报错），然后在spyder命令框输入python3 -m onepiece --help，会报错
【python3 -m onepiece --help
  File "<ipython-input-3-6553a9f4e9fe>", line 1
    python3 -m onepiece --help
                      ^
SyntaxError: invalid syntax】

**Comment by lossme** [comment]
`python3 -m onepiece --help`要是在命令行里执行的呀。

你说的spyder命令框，那个应该是ipython交互式解释器，是用来调试python代码的。

代码跟命令不好搞混

**Comment by niuqudechongdong** [comment]
哦，原来是命令行窗口，还是第一次在命令行窗口运行程序，等过几天有时间再好好研究一下。最后谢谢大佬~~

**Comment by niuqudechongdong** [comment]
谢谢大佬，可以下载了。不过在用邮箱时遇到了一个错误，输入‘python3 -m onepiece --comicid=543838 --pdf --mail’会报错
【UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 43: illegal multibyte sequence】。再次感谢大佬

**Comment by lossme** [comment]
可能是配置文件`config.ini`编码问题，文件编码要改成UTF8

**Comment by niuqudechongdong** [comment]
是编码的问题，不过要把文件编码改成ANSI格式才行
