### ISSUE TITLE
当章节名带有英文分号，且分号后带有空格时会出现错误

### ISSUE THREAD

**Issue by MetLee** [lossme/TencentComicBook#16]
https://github.com/lossme/TencentComicBook/blob/371f065e1f5296f46f466ddfe5a5070d813bf020/onepiece/site/u17.py#L116

例如下载雏蜂第19章时，`image_config`中下一章（`next_chapter`）章节名为《17_MI12: 危情300秒（上）》，该行代码会匹配以上内容，将其转换为《"17_MI12":危情300秒（上）》，使该项变为`"name":""17_MI12":危情300秒（上）"`，造成json库报错。

可以在该行之前将`"name"`后的value中的`: `替换为`:`：
`image_config_str = re.sub(r'("name":".*?):\s+(.*?")', r'\1:\2', image_config_str)`

**Comment by lossme** [comment]
之前处理这种非标准json字符串（key不带引号）方式有问题。，现在改用另外一种方法处理

**Comment by MetLee** [comment]
好的辛苦了

PS：
https://github.com/lossme/TencentComicBook/blob/5b9f10863118e20ec3f83b825ff768dc131c20db/onepiece/site/u17.py#L34
我这里刚准备提pr就被改过来了哈哈
