### ISSUE TITLE
脚本好像被有妖气ban了，SSL认证不通过/certificate verify failed，有无修复方案

### ISSUE THREAD

**Issue by cytuslee** [lossme/TencentComicBook#18]

**Comment by lossme** [comment]
更新下代码试试，加上 --noverify 参数
如`python -m onepiece --site u17 -id 195 -c 1 --noverify`

**Comment by cytuslee** [comment]
没有此参数，方便加qq交流么------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Key&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月27日(星期一) 晚上11:27
收件人:&nbsp;&quot;lossme/TencentComicBook&quot;<TencentComicBook@noreply.github.com&gt;;
抄送:&nbsp;&quot;cytuslee&quot;<727658355@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lossme/TencentComicBook] 脚本好像被有妖气ban了，SSL认证不通过/certificate verify failed，有无修复方案 (#18)

**Comment by cytuslee** [comment]
727658355

**Comment by lossme** [comment]
再更新下代码试下，刚才改完代码忘记推上来了orz

**Comment by cytuslee** [comment]
已成功，感谢大佬维护
