### ISSUE TITLE
B站内容图片需要token 而且所有图片都403了 希望作者检查下 谢谢！

### ISSUE THREAD

**Issue by chuihai** [lossme/TencentComicBook#19]
谢谢了

**Comment by lossme** [comment]
好像可以正常下载的呀，看看下载的什么漫画，报什么异常
把下载命令和错误信息发出来看看

**Comment by lossme** [comment]
更新下代码试试？

**Comment by chuihai** [comment]
非常感谢您的回复！忘了说明了 是API 程序是昨天安装的；
bilibili
例如 http://123.207.228.46:8001/comic/bilibili/28201/1 里面的图片，
 用chrome正常浏览器403 用 无痕模式就可以打开 不知道为什么哈，可能是缓存吧；
u17
http://123.207.228.46:8001/comic/u17/181558 这个正常但是章节就不行 
  http://123.207.228.46:8001/comic/u17/181558/1 提示 Internal Server Error

**Comment by lossme** [comment]
已更新修复

**Comment by lossme** [comment]
关于b站图片token过期的问题，已增加force_refresh参数表示刷新图片链接
如
```sh
curl "${host}/comic/bilibili/28201/1?force_refresh=true"
```
