### ISSUE TITLE
腾讯漫画章节列表含'预告'API数据就会缺少第一章

### ISSUE THREAD

**Issue by chuihai** [lossme/TencentComicBook#22]
作者你好！在使用腾讯API的时候我发现个小问题;
例如下面这部漫画: 
腾讯漫画 https://ac.qq.com/Comic/comicInfo/id/648164
腾讯官网的章节列表是 ------   预告 第一话 第二话 第三话 ......
API的章节列表是----- 预告 第二话 第三话 第四话......
经过三天的测试 发现 凡是章节列表中含有 预告 就会区少第一章;

希望作者有时间修复下 我们群内有很多人在使用你的APi 非常感谢 谢谢！

**Comment by lossme** [comment]
已经处理好了，更新下代码试下吧

**Comment by chuihai** [comment]
谢谢你！ 以修复了！
