### ISSUE TITLE
BiliBili onepiece.cli 182 [ERROR] please go to bilibili comics APP to read

### ISSUE THREAD

**Issue by summury1** [lossme/TencentComicBook#25]
环境：win10LTSB2019 /python3.8/powershell
使用命令：python -m onepiece --site=bilibili --comicid=mc27967 --chapter=all
下载部分后开始报错
![截图_2020-10-25_18-39-42](https://user-images.githubusercontent.com/46081566/97104803-9d7bd580-16f1-11eb-9baa-c7b25cdd5f7f.jpg)

**Comment by lossme** [comment]
![image](https://user-images.githubusercontent.com/12013826/97104964-b33dca80-16f2-11eb-9223-f720e6a8da50.png)
之后的章节是需要购买的，可以在源站购买正版。

**Comment by summury1** [comment]
感谢回复。以为用了限免卡就可以先下载保存了。

**Comment by summury1** [comment]
![截图_2020-10-25_19-34-58](https://user-images.githubusercontent.com/46081566/97105892-395d0f80-16f9-11eb-80c4-7c5c8a8c1796.jpg)
python -m onepiece --site=bilibili --comicid=mc27967 --chapter=9-100 --login --driver-path="C:\Users\N\Desktop\chromedriver.exe" --driver-type="Chrome" --session-path=".cache/session.pickle"
使用chromedriver登录后可以下载了
