### ISSUE TITLE
能否增加一个拼接下载后被裁切的长图重新合成的功能？

### ISSUE THREAD

**Issue by mikulolicon** [lossme/TencentComicBook#26]
示例漫画：https://manga.bilibili.com/detail/mc27809?from=manga_serach
上图这种漫画本来一话是单张的长图，下载后被裁切成了等宽不等高的多张图片，而且有的图片是被从一格漫画的正中间分割的（比如第231话），能否增加一个按照序号将其重新拼合为长图的命令呢？这样可以手动设置来应对这种长图漫画。

**Comment by mikulolicon** [comment]
感谢更新，测试了下，可以正常合并拼接。有个问题，就是合并的长图产生了明显的画面劣化现象，对比文件大小，比未合并的散图体积大概小了1/3左右，可以设定合成图片的质量吗？或者直接设置为PNG？

**Comment by lossme** [comment]
生成PNG图片的话，体积要大好几倍

**Comment by mikulolicon** [comment]
但是测试下，目前的参数，彩图画面劣化得比较明显，导出图片体积大还可以用xnconvert转换JPG控制体积，导出参数可以看图片情况。

**Comment by mikulolicon** [comment]
或者有参数可以设定合并的JPG质量吗，那样就一步到位了。

**Comment by lossme** [comment]
可以的

**Comment by mikulolicon** [comment]
感谢，测试了下，解决了合成问题。
