### ISSUE TITLE
发送邮件报错:535

### ISSUE THREAD

**Issue by diyhome** [lossme/TencentComicBook#3]
！error:(535, b'Error: authentication failed')
(535, b'Error: authentication failed')
按照readme安装了依赖

**Comment by lossme** [comment]
1. 首先检查邮件是否开启了POP3/SMTP/IMAP服务，
2. 可能是需要授权码登录，你可以尝试把配置文件里的密码更换为授权码。
qq授权码获取 https://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
![image](https://user-images.githubusercontent.com/12013826/53608578-4cef6480-3bfe-11e9-941f-dc1c337e9daa.png)
