### ISSUE TITLE
推荐加入 cocomanhua

### ISSUE THREAD

**Issue by 8108905** [lossme/TencentComicBook#30]
https://www.cocomanhua.com/ 

谢谢

**Comment by lossme** [comment]
暂时没好方案，用的是selenium来爬取，只支持命令行的方式下载，api调用方式不支持

**Comment by 8108905** [comment]
谢谢！ 127.0.0.1:3000/api/77mh/comic/157990/17 希望检查下这个。 其他章节ok 唯独这章节 谢谢

**Comment by 8108905** [comment]
http://www.acg456.com/HTML/HKDPD/
http://127.0.0.1:3000/api/acg456/comic/HKDPD
name: "çº¢å£³çæ½å¤æ",
title: "015è¯"
漫画标题 章节标题 乱码
