### ISSUE TITLE
__init__.py 中的requests 导入不进来

### ISSUE THREAD

**Issue by liangbinc** [lossme/TencentComicBook#4]
No module named 'requests'  ;我已经pip install， 自己单独文件测试没问题，整体运行是出现的

**Comment by lossme** [comment]
可能是依赖包没安装好。你可以重新按照readme说的步骤重新试一下。
或者可以贴出更详细的错误信息，方便定位和解决问题

**Comment by liangbinc** [comment]
File "E:/extra/cartoon-project/onepiece/__main__.py", line 3, in <module>
    from onepiece.cli import main
  File "E:\extra\cartoon-project\onepiece\cli.py", line 6, in <module>
    from .comicbook import ComicBook
  File "E:\extra\cartoon-project\onepiece\comicbook.py", line 6, in <module>
    from onepiece.req_test.image_cache import ImageCache
  File "E:\extra\cartoon-project\onepiece\req_test\image_cache.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'


D:\python_3.6\Scripts>pip install requests
Requirement already satisfied: requests in d:\python_3.6\lib\site-packages (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\python_3.6\lib\site-packages (from requests) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in d:\python_3.6\lib\site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in d:\python_3.6\lib\site-packages (from requests) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in d:\python_3.6\lib\site-packages (from requests) (2019.3.9)

**Comment by lossme** [comment]
```sh
>>> python3 -m pip install requests
>>> python3 -m onepiece
```
