### ISSUE TITLE
最后登录这块没看懂 怎么操作啊

### ISSUE THREAD

**Issue by coremaya** [lossme/TencentComicBook#8]

**Comment by lossme** [comment]
照着文档说的关于登录步骤，一步一步来。到最后输入命令会自动弹出浏览器打开登陆页面让你登录，登录成功之后再进行图片下载

**Comment by coremaya** [comment]
登录之后还是现实请到客户端观看

**Comment by lossme** [comment]
你说的是哔哩哔哩的吗，可能是人家的限制网页观看的。这个就没办法了

**Comment by coremaya** [comment]
> 你说的是哔哩哔哩的吗，可能是人家的限制网页观看的。这个就没办法了

我在网页可以看啊

**Comment by lossme** [comment]
给个链接，我看下。

**Comment by coremaya** [comment]
python -m onepiece --site=bilibili --comicid=24743 --chapter=279 --login --driver-path="chromedriver" --driver-type="Chrome" --session-path="C:\Users\wunan\Downloads\TencentComicBook-master\.cache\session.pickle"

**Comment by coremaya** [comment]
我这么输入对吗

**Comment by coremaya** [comment]
> 给个链接，我看下。
https://manga.bilibili.com/mc24743/220396?from=manga_detail

**Comment by lossme** [comment]
--driver-path="这里改成你下载的chromedriver的路径"

**Comment by coremaya** [comment]
> --driver-path="这里改成你下载的chromedriver的路径"

好

**Comment by coremaya** [comment]
> --driver-path="这里改成你下载的chromedriver的路径"

出错了，我原来那么输入能登录也现实登录成功 然后就是显示移到app观看

**Comment by lossme** [comment]
应该是要付费购买的章节。前提是你的账号需要先购买

**Comment by coremaya** [comment]
> 应该是要付费购买的章节。前提是你的账号需要先购买

我购买了 已经解锁

**Comment by coremaya** [comment]
> 应该是要付费购买的章节。前提是你的账号需要先购买

![image](https://user-images.githubusercontent.com/20692119/73609752-c613ea80-460b-11ea-99fa-2b2bd1791ee9.png)

**Comment by lossme** [comment]
> python -m onepiece --site=bilibili --comicid=24743 --chapter=279 --login --driver-path="chromedriver" --driver-type="Chrome" --session-path="C:\Users\wunan\Downloads\TencentComicBook-master.cache\session.pickle"

指令里的279是序号，跟页面显示的279不是同一个章节

**Comment by coremaya** [comment]
> > python -m onepiece --site=bilibili --comicid=24743 --chapter=279 --login --driver-path="chromedriver" --driver-type="Chrome" --session-path="C:\Users\wunan\Downloads\TencentComicBook-master.cache\session.pickle"
> 
> 指令里的279是序号，跟页面显示的279不是同一个章节

哦哦 原来 是不是每次下载都要输入这一长串

**Comment by lossme** [comment]
是的呢，记在笔记本里吧。279好像是对应 --chapter=300，不行的话再--chapter=279-xxx，这样一批的来

**Comment by coremaya** [comment]
> 是的呢，记在笔记本里吧。279好像是对应 --chapter=300，不行的话再--chapter=279-xxx，这样一批的来

好 我试试

**Comment by coremaya** [comment]
> > 是的呢，记在笔记本里吧。279好像是对应 --chapter=300，不行的话再--chapter=279-xxx，这样一批的来
> 
> 好 我试试

成功了 麻烦大佬了
